In [1]:
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
df_transactions = pd.read_excel('Lumen_Data_V.xlsx', sheet_name = 'Donornet Transactions')

In [3]:
df_transactions

,ID,Date,Contact,Email,Campaign,Item,Fund,Amount,Payment Method,Ref/Check#,Type,Recurring Payment ID
0,11199,2022-02-28,Alex Mundackal,smundackal@aol.com,Child Sponsorship,Credit Card Fees,Credit Card Fees,0.9,Online (Bluepay),101254682128,Payment,618.0
1,11200,2022-02-28,Alex Mundackal,smundackal@aol.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,30.0,Online (Bluepay),101254682128,Payment,618.0
2,11201,2022-02-28,Johney Simon,johneys98@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,90.0,Online (Bluepay),101254682507,Payment,32.0
3,11202,2022-02-28,Tony Antony,tonanto5@gmail.com,Child Sponsorship,Credit Card Fees,Credit Card Fees,0.9,Online (Bluepay),101254682568,Payment,166.0
4,11203,2022-02-28,Tony Antony,tonanto5@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,30.0,Online (Bluepay),101254682568,Payment,166.0
...,...,...,...,...,...,...,...,...,...,...,...,...
11240,1620,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,1.0,Online (Bluepay),100515877607,Refund,NaN
11241,1621,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,1.0,Online (Bluepay),100515878131,Refund,NaN
11242,1622,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,2.0,Online (Bluepay),100515878611,Refund,NaN
11243,1623,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,3.0,Online (Bluepay),100515878926,Refund,NaN
11244,10889,2021-12-30,Stephen Inasu,stepheninasu@gmail.com,Missionary Partnership,Missionary Partnership,Missionary Partnership,10000.0,Check,1787,Payment,NaN

In [4]:
df_contacts = pd.read_excel('Lumen_Data_V.xlsx', sheet_name = 'Donornet Contacts')

In [5]:
df_contacts

,ID,Firstname,Lastname,Email,Phone,Address1,Address2,City,State,Zip,Country,Gender,Date of Birth,Do Not Solicit,Notes,Status,Created Date,Modified Date
0,1109,Dayabindu,Charities,sonyjosef@gmail.com,9546551764,13127 Majestic Way,NaN,Cooper City,Florida,33026,Usa,NaN,NaT,0,NaN,Active,2022-02-24 17:22:16,2022-02-24 17:22:16
1,585,Jaimie,Kuriakose,jykuriakose@gmail.com,7088902296,5272 Lake BLVD,NaN,Delray Beach,FL,33484,United States,NaN,NaT,0,NaN,Active,2021-09-19 20:40:27,2022-02-05 01:53:19
2,425,Leslie,Thomas,lesliemaria09@gmail.com,2147093664,289 Orchard Lane,NaN,Sunnyvale,TX,75182,United States,Female,NaT,0,NaN,Active,2021-08-25 01:23:57,2022-02-04 21:18:26
3,966,Rons,Joseph,abhishron@yahoo.com,214-952-5455,1608 Wahl St. E,NaN,Irving,TX,75060,USA,Male,NaT,0,NaN,Active,2021-10-07 13:45:11,2022-02-01 18:01:52
4,548,Selcy,Joby,jobyagnes@gmail.com,No Phone,1238 Nocona Drive,NaN,Irving,Texas,75063,United States,NaN,NaT,0,NaN,Active,2021-09-17 04:11:37,2022-02-01 18:01:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,7,Sivachidhambaram,Natarajan,cnsiva@gmail.com,3129725580,3380 Hollis Cir,NaN,Naperville,Illinois,60564,United States,NaN,NaT,0,NaN,Active,2020-10-06 21:04:39,2020-10-06 21:04:39
996,5,Dibin,Pookombil,dibinp@gmail.com,9176035575,1309 Ponca St,NaN,Carrollton,TX,75010-1162,United States,Male,NaT,0,NaN,Active,2020-09-29 15:10:54,2020-09-29 15:10:54
997,2,Admin,User,finance@lumenvitae.us,9146488368,4622 NW 3rd Dr,NaN,Delray Beach,FL,33445,USA,Male,2000-01-01,1,NaN,Active,2020-01-01 00:00:00,2020-07-09 18:14:07
998,1,Annonymous,User,annonymous@donornet.work,123-456-7890,123 Noname St,NaN,Chicago,Illinois,60100,USA,Male,2000-01-01,1,NaN,Active,2020-01-01 00:00:00,2020-01-01 00:00:00
999,3,Support,User,support@donornet.work,123-456-7890,805 Spring Valley CT,NaN,Schaumburg,Illinois,60193,USA,Female,2000-01-01,1,NaN,Active,2020-01-01 00:00:00,2020-01-01 00:00:00

In [6]:
df_merged = df_transactions.merge(df_contacts, how = 'left', on = 'Email')

In [7]:
df_merged

,ID_x,Date,Contact,Email,Campaign,Item,Fund,Amount,Payment Method,Ref/Check#,...,State,Zip,Country,Gender,Date of Birth,Do Not Solicit,Notes,Status,Created Date,Modified Date
0,11199,2022-02-28,Alex Mundackal,smundackal@aol.com,Child Sponsorship,Credit Card Fees,Credit Card Fees,0.9,Online (Bluepay),101254682128,...,NY,12570,USA,NaN,NaT,0,NaN,Active,2021-11-15 04:29:55,2021-11-15 04:29:55
1,11200,2022-02-28,Alex Mundackal,smundackal@aol.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,30.0,Online (Bluepay),101254682128,...,NY,12570,USA,NaN,NaT,0,NaN,Active,2021-11-15 04:29:55,2021-11-15 04:29:55
2,11201,2022-02-28,Johney Simon,johneys98@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,90.0,Online (Bluepay),101254682507,...,NY,11040,United States,Male,NaT,0,NaN,Active,2020-11-28 16:34:40,2020-11-28 16:34:40
3,11202,2022-02-28,Tony Antony,tonanto5@gmail.com,Child Sponsorship,Credit Card Fees,Credit Card Fees,0.9,Online (Bluepay),101254682568,...,Texas,76053,United States,Male,NaT,0,NaN,Active,2021-08-29 17:58:38,2021-08-29 17:58:38
4,11203,2022-02-28,Tony Antony,tonanto5@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,30.0,Online (Bluepay),101254682568,...,Texas,76053,United States,Male,NaT,0,NaN,Active,2021-08-29 17:58:38,2021-08-29 17:58:38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11240,1620,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,1.0,Online (Bluepay),100515877607,...,FL,33445,USA,Male,1988-04-07,0,NaN,Active,2021-02-03 20:11:54,2021-02-03 20:11:54
11241,1621,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,1.0,Online (Bluepay),100515878131,...,FL,33445,USA,Male,1988-04-07,0,NaN,Active,2021-02-03 20:11:54,2021-02-03 20:11:54
11242,1622,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,2.0,Online (Bluepay),100515878611,...,FL,33445,USA,Male,1988-04-07,0,NaN,Active,2021-02-03 20:11:54,2021-02-03 20:11:54
11243,1623,2018-01-07,finance LV,bri847@gmail.com,Child Sponsorship,Child Sponsorship,Child Sponsorship,3.0,Online (Bluepay),100515878926,...,FL,33445,USA,Male,1988-04-07,0,NaN,Active,2021-02-03 20:11:54,2021-02-03 20:11:54
11244,10889,2021-12-30,Stephen Inasu,stepheninasu@gmail.com,Missionary Partnership,Missionary Partnership,Missionary Partnership,10000.0,Check,1787,...,NJ,8873,USA,Male,NaT,0,NaN,Active,2021-12-03 02:56:04,2021-12-03 02:56:04

In [8]:
df_merged.columns

Index(['ID_x', 'Date', 'Contact', 'Email', 'Campaign', 'Item', 'Fund',
       'Amount', 'Payment Method', 'Ref/Check#', 'Type',
       'Recurring Payment ID', 'ID_y', 'Firstname', 'Lastname', 'Phone',
       'Address1', 'Address2', 'City', 'State', 'Zip', 'Country', 'Gender',
       'Date of Birth', 'Do Not Solicit', 'Notes', 'Status', 'Created Date',
       'Modified Date'],
      dtype='object')

In [9]:
df_merged.drop(['ID_x', 'Email', 'Item', 'Fund', 'Payment Method', 'Ref/Check#', 'Type',
       'Recurring Payment ID', 'ID_y', 'Firstname', 'Lastname', 'Phone',
       'Address1', 'Address2', 'Zip', 'Country',
       'Date of Birth', 'Do Not Solicit', 'Notes', 'Status', 'Created Date',
       'Modified Date'], axis=1, inplace=True)

In [10]:
df_merged.to_csv('MapVis.csv',index=False)

In [11]:
df_circular = pd.read_excel('2021 Sponsorship Data.xlsx')

In [12]:
df_circular.head()

,Date Started,Email,# of Children Sponsored (DN),Children Sponsored,Ambassador,Recurring Amount,One Time Amount,Payment Type,City of Residence,State of Residence,Region
0,2019-11-01,ma.al.ar89@gmail.com,2,"Gycheline Zamor,Marly Orimond",Alejandra Maria Arias,30.0,360.0,Recurring Monthly Donornet,Newmanstown,PA,Philadelphia
1,2019-11-07,dasamuels0815@gmail.com,3,"Jefferson Riodin,Donaldo Maitre,Michaelle Joha...",NaN,190.0,0.0,Recurring Monthly Donornet,Lincoln Park,NJ,North NJ
2,2020-01-02,jobypanackal@hotmail.com,2,"Alain Charles Eugene,Magalie Louissaint",NaN,60.0,0.0,Recurring Monthly Donornet,NaN,NaN,South Florida
3,2020-01-09,poornimaroj81@gmail.com,1,Rose-Phine Saraphina NoÃ«l,NaN,30.0,0.0,Recurring Annual Donornet,Philadelphia,PA,Philadelphia
4,2020-01-29,lcyprsd@gmail.com,1,Christelle Lumene,NaN,30.0,0.0,Recurring Annual Donornet,Coral Springs,FL,South Florida

In [13]:
df_circular.drop('Email', axis=1, inplace =True)

In [14]:
df_circular

,Date Started,# of Children Sponsored (DN),Children Sponsored,Ambassador,Recurring Amount,One Time Amount,Payment Type,City of Residence,State of Residence,Region
0,2019-11-01,2,"Gycheline Zamor,Marly Orimond",Alejandra Maria Arias,30.0,360.0,Recurring Monthly Donornet,Newmanstown,PA,Philadelphia
1,2019-11-07,3,"Jefferson Riodin,Donaldo Maitre,Michaelle Joha...",NaN,190.0,0.0,Recurring Monthly Donornet,Lincoln Park,NJ,North NJ
2,2020-01-02,2,"Alain Charles Eugene,Magalie Louissaint",NaN,60.0,0.0,Recurring Monthly Donornet,NaN,NaN,South Florida
3,2020-01-09,1,Rose-Phine Saraphina NoÃ«l,NaN,30.0,0.0,Recurring Annual Donornet,Philadelphia,PA,Philadelphia
4,2020-01-29,1,Christelle Lumene,NaN,30.0,0.0,Recurring Annual Donornet,Coral Springs,FL,South Florida
...,...,...,...,...,...,...,...,...,...,...
654,2021-12-18,4,"Love Darlie Bejamin,Lourdjina Adelson,Yasmine ...",NaN,NaN,NaN,One Time Donornet,NaN,NaN,Chicago
655,2021-12-22,1,Obenson Paul,NaN,NaN,NaN,One Time Donornet,Frisco,TX,Dallas
656,2021-12-28,1,Alette Phalens,NaN,NaN,NaN,One Time Donornet,Reading,PA,Philadelphia
657,2021-12-30,1,Tracy Carla Constant,NaN,30.0,0.0,Recurring Monthly Donornet,Lansdale,PA,Philadelphia
658,2022-01-01,1,Valsimond Esperancie,NaN,0.0,360.0,One Time Donornet,Lilburn,GA,Atlanta

In [15]:
df_circular.to_csv('CircularRingVis.csv',index=False)